from enum import StrEnum

from pss_fleet_data.models.enums import ParameterInterval, ParameterOnMissing, UserAllianceMembership, UserAllianceMembershipEncoded


class ErrorCode(StrEnum):
    """
    An error code returned by the API when an error occurs.
    """

    FLEET_NOT_FOUND = "ALLIANCE_NOT_FOUND"
    COLLECTION_NOT_DELETED = "COLLECTION_NOT_DELETED"
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"
    CONFLICT = "CONFLICT"
    FORBIDDEN = "FORBIDDEN"
    FROM_DATE_AFTER_TO_DATE = "FROM_DATE_AFTER_TO_DATE"
    INVALID_BOOL = "INVALID_BOOL"
    INVALID_DATETIME = "INVALID_DATETIME"
    INVALID_JSON_FORMAT = "INVALID_JSON_FORMAT"
    INVALID_NUMBER = "INVALID_NUMBER"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INVALID_PARAMETER_FORMAT = "INVALID_PARAMETER_FORMAT"
    INVALID_PARAMETER_VALUE = "INVALID_PARAMETER_VALUE"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NON_UNIQUE_COLLECTION_ID = "NOT_UNIQUE_COLLECTION_ID"
    NON_UNIQUE_TIMESTAMP = "NON_UNIQUE_TIMESTAMP"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    NOT_FOUND = "NOT_FOUND"
    PARAMETER_ALLIANCE_ID_INVALID = "PARAMETER_ALLIANCE_ID_INVALID"
    PARAMETER_COLLECTION_ID_INVALID = "PARAMETER_COLLECTION_ID_INVALID"
    PARAMETER_DESC_INVALID = "PARAMETER_DESC_INVALID"
    PARAMETER_FROM_DATE_INVALID = "PARAMETER_FROM_DATE_INVALID"
    PARAMETER_FROM_DATE_TOO_EARLY = "PARAMETER_FROM_DATE_TOO_EARLY"
    PARAMETER_INTERVAL_INVALID = "PARAMETER_INTERVAL_INVALID"
    PARAMETER_ONMISSING_INVALID = "PARAMETER_ONMISSING_INVALID"
    PARAMETER_SKIP_INVALID = "PARAMETER_SKIP_INVALID"
    PARAMETER_TAKE_INVALID = "PARAMETER_TAKE_INVALID"
    PARAMETER_TO_DATE_INVALID = "PARAMETER_TO_DATE_INVALID"
    PARAMETER_TO_DATE_TOO_EARLY = "PARAMETER_TO_DATE_TOO_EARLY"
    PARAMETER_USER_ID_INVALID = "PARAMETER_USER_ID_INVALID"
    RATE_LIMITED = "RATE_LIMITED"
    SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    SERVER_ERROR = "SERVER_ERROR"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    UNSUPPORTED_SCHEMA = "UNSUPPORTED_SCHEMA"
    PLAYER_NOT_FOUND = "USER_NOT_FOUND"


class OperationId(StrEnum):
    """
    An `operation_id` of an API endpoint.
    """

    DELETE_DASHBOARD_USER = "DeleteDashboardUser"
    DELETE_FAVORITE_ALLIANCE = "DeleteFavoriteAlliance"
    DELETE_FAVORITE_USER = "DeleteFavoriteUser"
    GET_ALLIANCE_FROM_COLLECTION = "GetAllianceFromCollection"
    GET_ALLIANCE_HISTORY = "GetAllianceHistory"
    GET_ALLIANCES_FROM_COLLECTION = "GetAlliancesFromCollection"
    GET_COLLECTION = "GetCollection"
    GET_COLLECTIONS = "GetCollections"
    GET_HOME_PAGE = "GetHomePage"
    GET_PING = "GetPing"
    GET_PLAYER_FROM_COLLECTION = "GetPlayerFromCollection"
    GET_PLAYER_HISTORY = "GetPlayerHistory"
    GET_PLAYERS_FROM_COLLECTION = "GetPlayersFromCollection"
    GET_SEARCH_PLAYERS = "GetSearchPlayers"
    GET_TOP_100_PLAYERS_FROM_COLLECTION = "GetTop100PlayersFromCollection"
    INSERT_DASHBOARD_USER = "InsertDashboardUser"
    INSERT_FAVORITE_ALLIANCE = "InsertFavoriteAlliance"
    INSERT_FAVORITE_USER = "InsertFavoriteUser"
    UPDATE_DASHBOARD_USER = "UpdateDashboardUser"


__all__ = [
    "ErrorCode",
    "OperationId",
    "ParameterInterval",
    "ParameterOnMissing",
    "UserAllianceMembership",
    "UserAllianceMembershipEncoded",
]
